In [25]:
import numpy as np

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 15, 17, 19, 23])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(10,)

In [6]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
array2.shape

(3, 4)

ndarray => n dimentional array (n차원 배열)

In [10]:
array2.size

12

## 파이썬 리스트를 통해 생성

In [11]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
    
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


## 균일한 값으로 생성

In [12]:
array1 = numpy.full(6, 7)
    
print(array1)

[7 7 7 7 7 7]


### 모든 값이 0인 numpy array 생성

In [13]:
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)
    
print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


### 모든 값이 1인 numpy array 생성

In [14]:
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)
    
print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


### 랜덤한 값들로 생성

In [15]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)
    
print(array1)
print()
print(array2)

[0.42847267 0.49512003 0.62616795 0.52498961 0.02998801 0.83604807]

[0.3942371  0.20702924 0.84884438 0.41053434 0.80118134 0.08663292]


## 연속된 값들이 담긴 Numpy array 생성

In [16]:
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


### 파라미터 2개

In [17]:
array1 = numpy.arange(2, 7)
print(array1)

[2 3 4 5 6]


### 파라미터 3개

In [18]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


## 인덱싱, 슬라이싱

In [31]:
array1 = np.array([2, 3, 5, 7, 11, 13, 15])

In [32]:
array1[0]

2

In [33]:
array1[-1]

15

In [34]:
array1[[1, 3, 4]]

array([ 3,  7, 11])

In [35]:
array2 = np.array([2, 1, 3])

In [36]:
array1[array2]

array([5, 3, 7])